### PR TITLE
Additional text options

### PR DESCRIPTION
**Pull request by JessicaTheGunLady**
Didn't plan on doing this but Frit threatened to shoot me if I didn't.

### CODE REVIEW

**Comment by malicean** [comment]
There's definitely some room for improvement here, especially the rounding, but the content of it is great. I'll see about cleaning this up and merging it within the week.

**Comment by JessicaTheGunLady** [comment]
> There's definitely some room for improvement here, especially the rounding, but the content of it is great. I'll see about cleaning this up and merging it within the week.

That's fair, honestly I'm surprised what I wrote worked the first time... Aside from the percentages which tried their best to not work the way I wanted. p a i n

also almost pressed close with comment, whoops, I am a professional Github user

**Comment by malicean** [comment]
I'ma be honest, I forgot about this. It should be an easy test so I'll see if I can do it today.

also your fix commit won't work either lol

**Comment by JessicaTheGunLady** [comment]
> also your fix commit won't work either lol

figured lmao

**Comment by malicean** [comment]
Well I wasn't able to get anyone to test it and I don't have the time, but I don't write bugs so I don't need to test.

**Pull request merged**
